# Let's Chat: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: docker-compose up

app:
  build: ./docker
  links:
    - mongo
  ports:
    - 80:8080
    - 5222:5222
  command: ls .


mongo:
  image: mongo:latest
  ports :
    - 27017:27017
